#!/bin/csh -f
if (-f a.junk) \rm a.junk
../..//bin/focplt << EOT > a.junk
/* To see output on screen, take out the > a.junk
/*    and delete second line in this file
/* Printed output is in a file focplt.lst -- renamed in last line
n	Upper hemisphere projection?..[N]
y	Plot polarity data?
/*  Next entry is input polarity plot file name
focmec_all.inp
y	Desired file?..[Y]
y	Plot impulsive P polarities?..[Y]
0.1	Enter size for impulsive P polarities [0.25]
	linewidth for impulsive P polarities..[1]
n     emergent P?
n	Plot impulsive SH polarities?..[Y]
n	Plot impulsive SV polarities?..[Y]
	linewidth for circle outline..[2]
n	Add a title?..[Y]
n	Add time & file name? ..[y]
n	Add more data to plot?..[Y]
y       Plot focal mechanism solutions?..[Y]
y       Print/display solution summaries?..[N]
n       Plot P, T and B axes?  [Y]
y       P nodal planes..[Y]
y       Dashed Line?..[N]
0.02	length of dahs [0.1]
0.02	space between dashes [0.1]
1	Linewidth for solutions ... [1]
y	on same plot as data?..[Y]
n   Input solutions from a file?..[Y]
76.17   55.86  -64.11    final CNT solutioon
y	More solutions?
n       Plot P, T and B axes?  [Y]
y       P nodal planes..[Y]
n       Dashed Line?..[N]
1	Linewidth for solutions ... [1]
n   Input solutions from a file?..[Y]
76.43   59.08  -64.23   14.51     11/11    0.0852 best free
y	More solutions?
n       Plot P, T and B axes?  [Y]
y       P nodal planes..[Y]
y       Dashed Line?..[N]
0.15	length of dahs [0.1]
0.02	space between dashes [0.1]
1	Linewidth for solutions ... [1]
n       Input solutions from a file?..[Y]
78.81   217.07   148.41  NEIC/QED 1990 solution
n	More solutions? [N]
y	Add a plot label?
-2.0 2.2       X and Y positions for label
b)
n       Change from defaults for penwidth, height and angle?
y       cursor in lower left-hand corner
n	Add a plot label?
EOT
mv focplt.lst plot_all-P.lst
mv temp.sgf plot_all-P.sgf
../../bin/sgftopdf plot_all-P
