#!/bin/csh -f
if (-f a.junk) \rm a.junk
../../bin/focplt << EOT > a.junk
/* To see output on screen, take out the > a.junk
/*    and delete second line in this file
/* Printed output is in a file focplt.lst -- renamed in last line
n	Upper hemisphere projection?..[N]
y	Plot polarity data?
/*  Next entry is input polarity plot file name
focmec_8sta-noratios.inp
y	Desired file?..[Y]
y	Plot impulsive P polarities?..[Y]
0.15	Enter size for impulsive P polarities [0.25]
	linewidth for impulsive P polarities..[1]
n	Plot impulsive SH polarities?..[Y]
n	Plot impulsive SV polarities?..[Y]
	linewidth for circle outline..[2]
n	Add a title?..[Y]
n	Add time & file name? ..[y]
n	Add more data to plot?..[Y]
y       Plot focal mechanism solutions?..[Y]
y       Print/display solution summaries?..[N]
n       Plot P, T and B axes?  [Y]
y       P nodal planes..[Y]
n       Dashed Line?..[N]
1	Linewidth for solutions ... [1]
y	on same plot as data?
y   Input solutions from a file?..[Y]
/* Filespec for file with solutions
focmec_8sta-noratios.out
y       Correct file?..[Y]
n	Include time & file name?..[Y]
n	More solutions? [N]
y	Add a plot label?
-2.0 2.2       X and Y positions for label
a)
n       Change from defaults for penwidth, height and angle?
y       cursor in lower left-hand corner
n	Add a plot label?
EOT
mv focplt.lst plot_8sta-noratios.lst
mv temp.sgf plot_8sta-noratios.sgf
../../bin/sgftopdf plot_8sta-noratios
