#!/bin/csh -f
if (-f a.junk) \rm a.junk
../../bin/focmec << EOT > a.junk
focmec_UW-4.out
Event 8703270729 4 UW errors max
\* Comment is previous line: Input file for focmec is next
8703270729.inp
	correct file  [y]
y     Include emergent arrivals?...[Y]
n	relative weighting..[y]
4	allowed P polarity erors..[0]
	exit after this many acceptable solutions...[100]
	minimum B trend  [0]
	B increment  [5]
	maximum B trend  [355]
	min B plunge..[0]
	increment  [5]
	maximum..[90]
	minimum Angle..[0]
	increment  [5]
	maximum  [175]
EOT
mv focmec.lst focmec_UW-4.lst
