#!/bin/csh -f
if (-f a.junk) \rm a.junk
../../bin/focmec << EOT > a.junk
focmec_UW-1_ne.out
Event 8703270729 1 UW error max, no emergent arrivals
\* Comment is previous line: Input file for focmec is next
8703270729.inp
	correct file  [y]
n     Include emergent arrivals?...[Y]
1	relative weighting..[n]
1	allowed P polarity erors..[0]
500	exit after this many acceptable solutions...[100]
	minimum B trend  [0]
	B increment  [5]
	maximum B trend  [355]
	min B plunge..[0]
	increment  [5]
	maximum..[90]
	minimum Angle..[0]
	increment  [5]
	maximum  [175]
EOT
mv focmec.lst focmec_UW-1_ne.lst
